name: Setup Node Environment
description: Setup workspace

runs:
  using: composite
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        corepack enable
        corepack prepare --activate
        pnpm install --frozen-lockfile
