export {
  AddUserDark,
  AddUserLight,
  CreateDataDark,
  CreateDataLight,
  CreateDesktopDark,
  CreateDesktopLight,
  CreateFileMissingDark,
  CreateFileMissingLight,
  CreateNoConnectionDark,
  CreateNoConnectionLight,
  DataDark,
  DataLight,
  EmptyFolderDark,
  EmptyFolderLight,
  EmptyGeneralDark,
  EmptyGeneralLight,
  EmptySpaceDark,
  EmptySpaceLight,
  LaunchDark,
  LaunchLight,
  NoAccessDark,
  NoAccessLight,
  NoMatchDark,
  NoMatchLight,
  OrganizationDark,
  OrganizationLight,
  SearchDark,
  SearchLight,
} from "./illustrations/chunk-0";
export type { AxisIllustrationProps } from "./utils/types";
