import {
  AddUserProfileDark,
  AddUserProfileLight,
  bundleIllustrationSmart,
  DataDark,
  DataLight,
  DevicesDark,
  DevicesLight,
  EmptyFolderDark,
  EmptyFolderLight,
  EmptyGeneralDark,
  EmptyGeneralLight,
  EmptySpaceDark,
  EmptySpaceLight,
  FileMissingDark,
  FileMissingLight,
  NoAccessDark,
  NoAccessLight,
  NoConnectionDark,
  NoConnectionLight,
  NoContentDark,
  NoContentLight,
  NoMatchDark,
  NoMatchLight,
  NoSitesDark,
  NoSitesLight,
  NotFoundDark,
  NotFoundLight,
  SettingsDark,
  SettingsLight,
  SuccessDark,
  SuccessLight,
  TeamDark,
  TeamLight,
  UnderConstructionDark,
  UnderConstructionLight,
  MediaLight,
  MediaDark,
} from "@axiscommunications/fluent-illustrations";

export const Illustration = {
  "add-user-profile": bundleIllustrationSmart(
    AddUserProfileDark,
    AddUserProfileLight
  ),
  data: bundleIllustrationSmart(DataDark, DataLight),
  devices: bundleIllustrationSmart(DevicesDark, DevicesLight),
  "empty-folder": bundleIllustrationSmart(EmptyFolderDark, EmptyFolderLight),
  "empty-space": bundleIllustrationSmart(EmptySpaceDark, EmptySpaceLight),
  "file-missing": bundleIllustrationSmart(FileMissingDark, FileMissingLight),
  general: bundleIllustrationSmart(EmptyGeneralDark, EmptyGeneralLight),
  "no-access": bundleIllustrationSmart(NoAccessDark, NoAccessLight),
  "no-connection": bundleIllustrationSmart(NoConnectionDark, NoConnectionLight),
  "no-content": bundleIllustrationSmart(NoContentDark, NoContentLight),
  "no-match": bundleIllustrationSmart(NoMatchDark, NoMatchLight),
  "no-sites": bundleIllustrationSmart(NoSitesDark, NoSitesLight),
  "not-found": bundleIllustrationSmart(NotFoundDark, NotFoundLight),
  settings: bundleIllustrationSmart(SettingsDark, SettingsLight),
  success: bundleIllustrationSmart(SuccessDark, SuccessLight),
  media: bundleIllustrationSmart(MediaDark, MediaLight),
  team: bundleIllustrationSmart(TeamDark, TeamLight),
  "under-construction": bundleIllustrationSmart(
    UnderConstructionDark,
    UnderConstructionLight
  ),
} as const;
