name: Verify tokens

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare --activate
          pnpm install --frozen-lockfile

      - name: Build theme library and token generator
        run: pnpm --filter @axiscommunications/fluent-theme build

      - name: Transform Fluent Theme to JSON, builds tokens for platforms
        run: pnpm --filter @axiscommunications/fluent-theme tokens

