name: Verify illustrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Transform SVG to react components
        run: pnpm --filter @axiscommunications/fluent-illustrations illustrations:build-react

      - name: Build
        run: pnpm --filter @axiscommunications/fluent-illustrations build

      - name: Lint
        run: pnpm --filter @axiscommunications/fluent-illustrations lint
