name: Verifies gh-page is up and running

on:
  schedule:
    - cron: "0 */4 * * 1-5"
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]
    branches:
      - "main"

jobs:
  verify-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Run Playwright tests
        run: pnpm stest
        working-directory: ./examples

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: examples/test-results/*
          retention-days: 3

      - name: Notify in Teams
        if: failure()
        uses: ./.github/actions/notify-teams
        id: notify-teams
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_DEV }}
          summary: "${{ github.workflow }} ${{ github.job }} failed"
          notification_summary: "${{ github.job }} failed!"
          github: ${{ toJson(github) }}
          steps: ${{ toJson(steps) }}
