name: Verifies gh-page is up and running

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Delay start
      #   run: sleep 30s
      #   shell: bash

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare --activate
          pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test
        working-directory: ./examples

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-results/*
          retention-days: 5
          working-directory: ./examples
