name: Verify code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-commit-and-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup.yml

      - name: Check commit message
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm commitlint ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

      - name: Check unused dependencies
        run: |
          git diff --exit-code
          pnpm check:unused-deps

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup.yml

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup.yml

      - name: Run Tests
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup.yml

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm build
