name: Verify tokens

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Build theme library and token generator
        run: pnpm --filter @axiscommunications/fluent-theme build

      - name: Transform Fluent Theme to JSON, builds tokens for platforms
        run: pnpm --filter @axiscommunications/fluent-theme tokens

