name: Verify icons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Transform SVG to fonts
        run: pnpm --filter @axiscommunications/fluent-icons fonts:build

      - name: Transform SVG to react components
        run: pnpm --filter @axiscommunications/fluent-icons react:build

      - name: Build
        run: pnpm --filter @axiscommunications/fluent-icons build

      - name: Lint
        run: pnpm --filter @axiscommunications/fluent-icons lint
