name: Verify illustrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare --activate
          pnpm install --frozen-lockfile

      - name: Transform SVG to react components
        run: pnpm --filter @axiscommunications/fluent-illustrations illustrations:build-react

      - name: Build
        run: pnpm --filter @axiscommunications/fluent-illustrations build

      - name: Lint
        run: pnpm --filter @axiscommunications/fluent-illustrations lint
