name: Verify code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
              
      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Check commit message
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm commitlint ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Lint
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm build
          pnpm check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-workspace

      - name: Test
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          git diff --exit-code
          pnpm build
          pnpm test